export const words1 = [
  {
    key: 1,
    word: "아이",
    unit: "(1-1)1",
    translation: "ребенок",
  },
  {
    key: 2,
    word: "여우",
    unit: "(1-1)1",
    translation: "лиса",
  },
  {
    key: 3,
    word: "오",
    unit: "(1-1)1",
    translation: "пять",
  },
  {
    key: 4,
    word: "오이",
    unit: "(1-1)1",
    translation: "огурец",
  },
  {
    key: 5,
    word: "이",
    unit: "(1-1)1",
    translation: "два",
  },
  {
    key: 6,
    word: "우유",
    unit: "(1-1)1",
    translation: "молоко",
  },
];

export const words2 = [
  {
    key: 7,
    word: "나무",
    unit: "(1-1)2",
    translation: "дерево",
  },
  {
    key: 8,
    word: "나비",
    unit: "(1-1)2",
    translation: "бабочка",
  },
  {
    key: 9,
    word: "다리",
    unit: "(1-1)2",
    translation: "нога",
  },
  {
    key: 10,
    word: "머리",
    unit: "(1-1)2",
    translation: "голова",
  },
  {
    key: 11,
    word: "모자",
    unit: "(1-1)2",
    translation: "шляпа",
  },
  {
    key: 12,
    word: "하마",
    unit: "(1-1)2",
    translation: "бегемот",
  },
  {
    key: 13,
    word: "바지",
    unit: "(1-1)2",
    translation: "брюки",
  },
  {
    key: 14,
    word: "하나",
    unit: "(1-1)2",
    translation: "один",
  },
  {
    key: 15,
    word: "어머니",
    unit: "(1-1)2",
    translation: "мать",
  },
  {
    key: 16,
    word: "아버지",
    unit: "(1-1)2",
    translation: "отец",
  },
  {
    key: 17,
    word: "사자",
    unit: "(1-1)2",
    translation: "лев",
  },
  {
    key: 18,
    word: "학원",
    unit: "(1-1)2",
    translation: "академия, частные курсы",
  },
  {
    key: 19,
    word: "허리",
    unit: "(1-1)2",
    translation: "талия",
  },
];

export const words3 = [
  {
    key: 20,
    word: "기차",
    unit: "(1-1)3",
    translation: "поезд",
  },
  {
    key: 21,
    word: "꼬리",
    unit: "(1-1)3",
    translation: "хвост",
  },
  {
    key: 22,
    word: "머리띠",
    unit: "(1-1)3",
    translation: "ободок",
  },
  {
    key: 23,
    word: "뽀뽀",
    unit: "(1-1)3",
    translation: "поцелуйчики",
  },
  {
    key: 24,
    word: "아빠",
    unit: "(1-1)3",
    translation: "папа",
  },
  {
    key: 25,
    word: "치마",
    unit: "(1-1)3",
    translation: "юбка",
  },
  {
    key: 26,
    word: "커피",
    unit: "(1-1)3",
    translation: "кофе",
  },
  {
    key: 27,
    word: "토끼",
    unit: "(1-1)3",
    translation: "заяц",
  },
  {
    key: 28,
    word: "토마토",
    unit: "(1-1)3",
    translation: "томат",
  },
  {
    key: 29,
    word: "포도",
    unit: "(1-1)3",
    translation: "виноград",
  },
];

export const words4 = [
  {
    key: 30,
    word: "개",
    unit: "(1-1)4",
    translation: "собака",
  },
  {
    key: 31,
    word: "과자",
    unit: "(1-1)4",
    translation: "снэк, печеньки",
  },
  {
    key: 32,
    word: "그네",
    unit: "(1-1)4",
    translation: "качели",
  },
  {
    key: 33,
    word: "사과",
    unit: "(1-1)4",
    translation: "яблоко",
  },
  {
    key: 34,
    word: "새",
    unit: "(1-1)4",
    translation: "птица",
  },
  {
    key: 35,
    word: "시계",
    unit: "(1-1)4",
    translation: "часы",
  },
  {
    key: 36,
    word: "여자",
    unit: "(1-1)4",
    translation: "женщина",
  },
  {
    key: 37,
    word: "의자",
    unit: "(1-1)4",
    translation: "стул",
  },
  {
    key: 38,
    word: "주사위",
    unit: "(1-1)4",
    translation: "игра в кости",
  },
  {
    key: 39,
    word: "카메라",
    unit: "(1-1)4",
    translation: "фотоаппарат",
  },
  {
    key: 40,
    word: "케이크",
    unit: "(1-1)4",
    translation: "торт",
  },
];

export const words5 = [
  {
    key: 41,
    word: "가방",
    unit: "(1-1)5",
    translation: "сумка",
  },
  {
    key: 42,
    word: "강",
    unit: "(1-1)5",
    translation: "река",
  },
  {
    key: 43,
    word: "곰",
    unit: "(1-1)5",
    translation: "медведь",
  },
  {
    key: 44,
    word: "공",
    unit: "(1-1)5",
    translation: "мяч",
  },
  {
    key: 45,
    word: "구름",
    unit: "(1-1)5",
    translation: "облако",
  },
  {
    key: 46,
    word: "김치",
    unit: "(1-1)5",
    translation: "кимчи",
  },
  {
    key: 47,
    word: "눈",
    unit: "(1-1)5",
    translation: "глаз, снег",
  },
  {
    key: 48,
    word: "달",
    unit: "(1-1)5",
    translation: "луна",
  },
  {
    key: 49,
    word: "말",
    unit: "(1-1)5",
    translation: "лошадь",
  },
  {
    key: 50,
    word: "물고기",
    unit: "(1-1)5",
    translation: "рыба",
  },
  {
    key: 51,
    word: "안경",
    unit: "(1-1)5",
    translation: "очки",
  },
  {
    key: 52,
    word: "엄마",
    unit: "(1-1)5",
    translation: "мама",
  },
  {
    key: 52,
    word: "친구",
    unit: "(1-1)5",
    translation: "друг",
  },
  {
    key: 53,
    word: "하늘",
    unit: "(1-1)5",
    translation: "небо",
  },
];

export const words6 = [
  {
    key: 54,
    word: "가족",
    unit: "(1-1)6",
    translation: "семья",
  },
  {
    key: 55,
    word: "꽃",
    unit: "(1-1)6",
    translation: "цветок",
  },
  {
    key: 56,
    word: "낚시",
    unit: "(1-1)6",
    translation: "рыбалка",
  },
  {
    key: 57,
    word: "낮",
    unit: "(1-1)6",
    translation: "день",
  },
  {
    key: 58,
    word: "돋보기",
    unit: "(1-1)6",
    translation: "лупа",
  },
  {
    key: 59,
    word: "밥",
    unit: "(1-1)6",
    translation: "еда, рис",
  },
  {
    key: 60,
    word: "밥솥",
    unit: "(1-1)6",
    translation: "рисоварка",
  },
  {
    key: 61,
    word: "밭",
    unit: "(1-1)6",
    translation: "поле (для засева)",
  },
  {
    key: 62,
    word: "부엌",
    unit: "(1-1)6",
    translation: "кухня",
  },
  {
    key: 63,
    word: "빗",
    unit: "(1-1)6",
    translation: "расческа",
  },
  {
    key: 64,
    word: "빛",
    unit: "(1-1)6",
    translation: "свет",
  },
  {
    key: 65,
    word: "숲",
    unit: "(1-1)6",
    translation: "лес",
  },
  {
    key: 66,
    word: "앞",
    unit: "(1-1)6",
    translation: "спереди",
  },
  {
    key: 67,
    word: "옷",
    unit: "(1-1)6",
    translation: "одежда",
  },
  {
    key: 68,
    word: "있다",
    unit: "(1-1)6",
    translation: "есть/быть",
  },
  {
    key: 69,
    word: "잎",
    unit: "(1-1)6",
    translation: "лист",
  },
  {
    key: 70,
    word: "지갑",
    unit: "(1-1)6",
    translation: "кошелек",
  },
  {
    key: 71,
    word: "집",
    unit: "(1-1)6",
    translation: "дом",
  },
  {
    key: 72,
    word: "책",
    unit: "(1-1)6",
    translation: "книга",
  },
  {
    key: 73,
    word: "컵",
    unit: "(1-1)6",
    translation: "чашка, кружка",
  },
  {
    key: 74,
    word: "학교",
    unit: "(1-1)6",
    translation: "школа",
  },
  {
    key: 75,
    word: "히읗",
    unit: "(1-1)6",
    translation: "хиыт буква ㅎ",
  },
  //   {
  //     key: 76,
  //     word: "",
  //     unit: "(1-1)6",
  //     translation: "",
  //   },
  //   {
  //     key: 77,
  //     word: "",
  //     unit: "(1-1)6",
  //     translation: "",
  //   },
];
